version: "3.8"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.1.1-alpine
    volumes:
      - influxdb-lib:/var/lib/influxdb2
    env_file:
      - ./influx.env
    ports:
      - 8086:8086
    restart: always
    privileged: true

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.2
    volumes:
      - ./grafana/etc:/etc/grafana:ro
      - grafana-lib:/var/lib/grafana
      - grafana-log:/var/log/grafana
    links:
      - influxdb:influxdb
    env_file:
      - ./grafana.env
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    restart: always
    privileged: true

volumes:
  influxdb-lib:
    external: false

  grafana-lib:
    external: false

  grafana-log:
    external: false
